version: 2.1
jobs:
  build:
    docker:
    - image: perl/5.28-slim
    steps:
    - checkout
    - run:
        command: |
          cpanm Dist::Zilla
          cpanm -n $(dzil authordeps)
          cpanm --installdeps .
          dzil test
        name: Run tests
