version: 2.1
jobs:
  build:
    docker:
    - image: perl:5.28
    steps:
    - checkout
    - run:
        command: |
          cpanm -n Dist::Zilla
          cpanm -n $(dzil authordeps)
          cpanm --installdeps .
          dzil test
        name: Run tests
