version: 2.1
jobs:
  build:
    docker:
    - image: tm604/perl-dzil
    steps:
    - checkout
    - run:
        command: |
          cpanm -n $(dzil authordeps)
          cpanm --installdeps .
          dzil test
        name: Run tests
